const SUCCESS_RESPONSE_STATUS = "success";
const FAIL_RESPONSE_STATUS = "fail";
const ERROR_RESPONSE_STATUS = "error";

export { SUCCESS_RESPONSE_STATUS, FAIL_RESPONSE_STATUS, ERROR_RESPONSE_STATUS };
